- id: md_plantuml_converter
  name: Markdown Plantuml Converter
  description: Reads plantum markups in markdown documentation, parses them  and inserts a link to render the svg|png|jpg representation
  entry: mdplantuml
  language: node
  args: [--extension=png, --image-dir=gen_docs/assets/puml,  --prefix= ]    #types: ["markdown", "plantuml"]
  files:  \.md$